language: java
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip
  - unzip -qq apache-maven-3.5.3-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.3
  - export PATH=$M2_HOME/bin:$PATH
jdk:
  - oraclejdk8
  - openjdk8
env:
    - TEST_FOLDER=test/javaee8
install:
  - echo "Overriding default install"
script:
  - export BASE_DIR=`pwd`
  - echo $BASE_DIR
  - wget http://download.oracle.com/glassfish/5.0/release/glassfish-5.0.zip
  - unzip glassfish-5.0.zip
  - ls
  - export MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cl‌​i.transfer.Slf4jMave‌​nTransferListener=wa‌​rn" ; mvn -B clean install
addons:
  apt:
    packages:
    - libxml2-utils
